#pragma once

#include "common.h"
#include <string>

//  This holds a comment for a given address
//  User comments are created by the user
//	System comments are comments that are generated by the disassembler
class Comment
{
public:
	Comment(adrs_t adrs, const std::string& text, bool user)
	    : adrs_{ adrs }
	    , text_{ text }
	    , user_{ user }
	{
	}

	adrs_t adrs() const { return adrs_; }
	const std::string& text() const { return text_; }
	bool user() const { return user_; }

private:
	adrs_t adrs_;
	std::string text_;
	bool user_;
};
