#pragma once

#include "common.h"
#include <string>

//  This holds a comment for a given address
//  A comment can be automatic, meaning it was generated by the disassembler
//  Automatic comments are "less interessting" than user-generated ones
class Comment
{
public:
	Comment(adrs_t adrs, const std::string& text, bool automatic)
	    : adrs_{ adrs }
	    , text_{ text }
	    , automatic_{ automatic }
	{
	}

	adrs_t adrs() const { return adrs_; }
	const std::string& text() const { return text_; }
	bool automatic() const { return automatic_; }

private:
	adrs_t adrs_;
	std::string text_;
	bool automatic_;
};
